"""empty message

Revision ID: 82bbfa3a2aad
Revises: 8812515a972e
Create Date: 2026-06-03 16:48:17.762761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82bbfa3a2aad'
down_revision = '8812515a972e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('risk_assessments', schema=None) as batch_op:
        batch_op.alter_column('risk_tolerance_score',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('total_risk_score',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('risk_category_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.alter_column('risk_capacity_score',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('uuid',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('uuid',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.alter_column('risk_capacity_score',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('risk_assessments', schema=None) as batch_op:
        batch_op.alter_column('risk_category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('total_risk_score',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('risk_tolerance_score',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
