"""fix

Revision ID: 8378811e5209
Revises: 3751aa04d3f7
Create Date: 2026-06-14 21:28:53.354941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8378811e5209'
down_revision = '3751aa04d3f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_blocked_tokens')
    with op.batch_alter_table('blocked_tokens', schema=None) as batch_op:
        batch_op.alter_column('uuid',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('uuid',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('uuid',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('blocked_tokens', schema=None) as batch_op:
        batch_op.alter_column('uuid',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    op.create_table('_alembic_tmp_blocked_tokens',
    sa.Column('token_id', sa.INTEGER(), nullable=False),
    sa.Column('jti', sa.VARCHAR(length=36), nullable=False),
    sa.Column('uuid', sa.NUMERIC(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('expires_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('token_id'),
    sa.UniqueConstraint('jti')
    )
    # ### end Alembic commands ###
