"""empty message

Revision ID: c2d02dbb998f
Revises: 
Create Date: 2026-06-06 17:13:41.907841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2d02dbb998f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blocked_tokens',
    sa.Column('token_id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('token_id'),
    sa.UniqueConstraint('jti')
    )
    op.create_table('questions',
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('question_number', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('question_text_ar', sa.Text(), nullable=False),
    sa.Column('question_type', sa.Enum('Registration', 'Questionnaire', name='questiontype'), nullable=False),
    sa.Column('question_format', sa.Enum('MCQ', 'Scale', name='questionformat'), nullable=False),
    sa.PrimaryKeyConstraint('question_id'),
    sa.UniqueConstraint('question_text'),
    sa.UniqueConstraint('question_text_ar')
    )
    op.create_table('recommendation_sets',
    sa.Column('set_id', sa.Integer(), nullable=False),
    sa.Column('risk_category', sa.Enum('Conservative', 'Moderate', 'Aggressive', name='riskcat'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('set_id')
    )
    op.create_table('risk_categories',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('category_name', sa.Enum('Conservative', 'Moderate', 'Aggressive', name='riskcat'), nullable=False),
    sa.Column('category_name_ar', sa.Enum('محافظ', 'متوسط', 'جريء', name='riskcatar'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('description_ar', sa.Text(), nullable=False),
    sa.Column('min_score', sa.Integer(), nullable=False),
    sa.Column('max_score', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('category_id'),
    sa.UniqueConstraint('category_name'),
    sa.UniqueConstraint('category_name_ar')
    )
    op.create_table('sectors',
    sa.Column('sector_id', sa.Integer(), nullable=False),
    sa.Column('sector_name', sa.String(length=100), nullable=False),
    sa.Column('sector_name_ar', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('description_ar', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('sector_id'),
    sa.UniqueConstraint('sector_name'),
    sa.UniqueConstraint('sector_name_ar')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('options',
    sa.Column('option_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('option_number', sa.Integer(), nullable=False),
    sa.Column('option_text', sa.Text(), nullable=False),
    sa.Column('option_text_ar', sa.Text(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.question_id'], ),
    sa.PrimaryKeyConstraint('option_id')
    )
    op.create_table('risk_assessments',
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('risk_tolerance_score', sa.Integer(), nullable=True),
    sa.Column('total_risk_score', sa.Integer(), nullable=True),
    sa.Column('risk_category_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['risk_category_id'], ['risk_categories.category_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('assessment_id')
    )
    op.create_table('stocks',
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('ticker_symbol', sa.String(length=10), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('company_name_ar', sa.String(length=255), nullable=False),
    sa.Column('sector_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('description_ar', sa.Text(), nullable=False),
    sa.Column('risk_level', sa.Enum('Low', 'Medium', 'High', name='risklevel'), nullable=False),
    sa.Column('risk_level_ar', sa.Enum('منخفض', 'متوسط', 'مرتفع', name='risklevelar'), nullable=False),
    sa.ForeignKeyConstraint(['sector_id'], ['sectors.sector_id'], ),
    sa.PrimaryKeyConstraint('stock_id'),
    sa.UniqueConstraint('company_name'),
    sa.UniqueConstraint('company_name_ar'),
    sa.UniqueConstraint('ticker_symbol')
    )
    op.create_table('user_preferences',
    sa.Column('preference_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('language', sa.Enum('En', 'Ar', name='language'), nullable=False),
    sa.Column('notifications', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('preference_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('user_profiles',
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('risk_capacity_score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('profile_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('predictions',
    sa.Column('prediction_id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('predicted_return', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.stock_id'], ),
    sa.PrimaryKeyConstraint('prediction_id')
    )
    op.create_table('recommendations',
    sa.Column('recommendation_id', sa.Integer(), nullable=False),
    sa.Column('recommendation_set_id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('predicted_return', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['recommendation_set_id'], ['recommendation_sets.set_id'], ),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.stock_id'], ),
    sa.PrimaryKeyConstraint('recommendation_id')
    )
    op.create_table('stock_prices',
    sa.Column('price_id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('high_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('low_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('close_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.stock_id'], ),
    sa.PrimaryKeyConstraint('price_id')
    )
    op.create_table('user_responses',
    sa.Column('response_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('option_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['risk_assessments.assessment_id'], ),
    sa.ForeignKeyConstraint(['option_id'], ['options.option_id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.question_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('response_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_responses')
    op.drop_table('stock_prices')
    op.drop_table('recommendations')
    op.drop_table('predictions')
    op.drop_table('user_profiles')
    op.drop_table('user_preferences')
    op.drop_table('stocks')
    op.drop_table('risk_assessments')
    op.drop_table('options')
    op.drop_table('users')
    op.drop_table('sectors')
    op.drop_table('risk_categories')
    op.drop_table('recommendation_sets')
    op.drop_table('questions')
    op.drop_table('blocked_tokens')
    # ### end Alembic commands ###
