"""initial

Revision ID: 33745f1e117f
Revises: d3d4605075f9
Create Date: 2026-04-19 17:05:00.098776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33745f1e117f'
down_revision = 'd3d4605075f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('risk_categories', schema=None) as batch_op:
        batch_op.alter_column('category_name_ar',
               existing_type=sa.VARCHAR(length=12),
               type_=sa.Enum('محافظ', 'متوسط', 'جريء', name='riskcatar'),
               existing_nullable=False)

    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.alter_column('risk_level_ar',
               existing_type=sa.VARCHAR(length=6),
               type_=sa.Enum('منخفض', 'متوسط', 'مرتفع', name='risklevelar'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.alter_column('risk_level_ar',
               existing_type=sa.Enum('منخفض', 'متوسط', 'مرتفع', name='risklevelar'),
               type_=sa.VARCHAR(length=6),
               existing_nullable=False)

    with op.batch_alter_table('risk_categories', schema=None) as batch_op:
        batch_op.alter_column('category_name_ar',
               existing_type=sa.Enum('محافظ', 'متوسط', 'جريء', name='riskcatar'),
               type_=sa.VARCHAR(length=12),
               existing_nullable=False)

    # ### end Alembic commands ###
